### ISSUE TITLE
template issue on osx for ios project

### ISSUE THREAD

**Issue by glungtung** [elliotwoods/ofxSingleton#1]
Hi,
I had a build issue when compiling for an iOS project on OSX

OpenFrameworks/Master/addons/ofxSingleton/src/ofxSingleton/Register.cpp:8:1: Template specialization requires 'template<>'

I had to modify  OFXSINGLETON_DEFINE_UNMANAGED by adding template<> like this
# define OFXSINGLETON_DEFINE_UNMANAGED(X) template<> std::shared_ptr<X> ofxSingleton::UnmanagedSingleton<X>::getInstance() { \

...

**Comment by elliotwoods** [comment]
Heya!
Yes I've seen that one before too when testing on OSX.
It seems to build fine on Windows with that edit, so i've brought in the edit

**Comment by elliotwoods** [comment]
thank you for spotting and reporting!

**Comment by glungtung** [comment]
I get the same error & fix with
#define OFXSINGLETON_DEFINE(X) template <> ofxSingleton::Singleton<X>::SingletonStore \* ofxSingleton::Singleton<X>::singletonStore

**Comment by glungtung** [comment]
Also had to add "typename" keyword in Singleton.h for getSingletonStore() definition after "new"

```
    static SingletonStore * getSingletonStore() {
        if (!ClassType::singletonStore) {
            ClassType::singletonStore = new typename ClassType::SingletonStore();
        }
```

**Comment by glungtung** [comment]
Despite this, I failed using it, got errors with singletonStore, and finally used UnmanagedSingleton successfully
Thanks !

**Comment by elliotwoods** [comment]
OK. Sorry to hear.
Managed singletons are only really needed in special circumstances (e.g.
Automatically sync singletons between dynamically loaded libraries).

I'll add an issue that OSX/iOS support needs to be tested

Thank you
Elliot
